# Generated by Django 3.2.8 on 2021-10-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_application', '0005_auto_20211016_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(blank=True, max_length=264, null=True, unique=True),
        ),
    ]
