# Generated by Django 3.2.8 on 2021-10-16 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_application', '0006_alter_application_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='application',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='user',
        ),
    ]
