# Generated by Django 3.2.8 on 2021-10-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_application', '0008_alter_subscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='framework',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
