# Generated by Django 3.2.8 on 2021-10-16 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_application', '0009_auto_20211017_0154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='updated_at',
            new_name='created_at',
        ),
    ]
